//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommissionerPolice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationDetail
    {
        public int ApplicantId { get; set; }
        public string ApplicationNo { get; set; }
        public string FunctionType { get; set; }
        public string Name { get; set; }
        public string FathersName { get; set; }
        public string Address { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> Ps_Id { get; set; }
        public string MobileNo { get; set; }
        public Nullable<System.DateTime> FunctionDate { get; set; }
        public string FromTime { get; set; }
        public string ToTime { get; set; }
        public string Duration { get; set; }
        public string Venue { get; set; }
        public Nullable<int> TotalSittingCapacity { get; set; }
        public string WorkingPlaceSize { get; set; }
        public Nullable<int> TotalParticipant { get; set; }
        public string IdProof { get; set; }
        public string AddressProof { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}
