//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommissionerPolice.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ePermissionEntities : DbContext
    {
        public ePermissionEntities()
            : base("name=ePermissionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationDetail> ApplicationDetails { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<FileType> FileTypes { get; set; }
        public virtual DbSet<ParticipantDetail> ParticipantDetails { get; set; }
        public virtual DbSet<PoliceStattion> PoliceStattions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<vw_ApplicationDetail> vw_ApplicationDetail { get; set; }
    
        public virtual ObjectResult<sp_ApplicationDetail_Result> sp_ApplicationDetail(Nullable<int> applicationid)
        {
            var applicationidParameter = applicationid.HasValue ?
                new ObjectParameter("applicationid", applicationid) :
                new ObjectParameter("applicationid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ApplicationDetail_Result>("sp_ApplicationDetail", applicationidParameter);
        }
    
        public virtual ObjectResult<sp_ParticipantDetail_Result> sp_ParticipantDetail(Nullable<int> applicationid)
        {
            var applicationidParameter = applicationid.HasValue ?
                new ObjectParameter("applicationid", applicationid) :
                new ObjectParameter("applicationid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ParticipantDetail_Result>("sp_ParticipantDetail", applicationidParameter);
        }
    }
}
