//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommissionerPolice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantDetail
    {
        public int ParticipantId { get; set; }
        public Nullable<int> ApplicantId { get; set; }
        public string ParticipantName { get; set; }
        public Nullable<int> Age { get; set; }
        public string MobileNo { get; set; }
        public string NativeDistrict { get; set; }
        public string PermissionFrom { get; set; }
        public string PermissionTo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    }
}
