//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommissionerPolice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ApplicationDetail
    {
        public int ApplicantId { get; set; }
        public string ApplicationNo { get; set; }
        public string FunctionType { get; set; }
        public string Name { get; set; }
        public string MobileNo { get; set; }
        public Nullable<int> Ps_Id { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string FunctionDate { get; set; }
        public Nullable<System.DateTime> Funcdt { get; set; }
        public string Status { get; set; }
    }
}
